apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.kubernetes.io/upcloud-load-balancer-config: |
      {
        "name": "app-service-lb",
        "frontends": [
          {
            "name": "https",
            "mode": "http",
            "port": 443,
            "rules": [
              {
                "name": "add-ip-header",
                "priority": 100,
                "matchers": [],
                "actions": [
                  {
                    "type": "set_forwarded_headers",
                    "action_set_forwarded_headers": {}
                  }
                ]
              }
            ]
          },
          {
            "name": "http",
            "mode": "http",
            "port": 80,
            "rules": [
              {
                "name": "redirect-to-https",
                "priority": 100,
                "matchers": [],
                "actions": [
                  {
                    "type": "http_redirect",
                    "action_http_redirect": {
                      "scheme": "https"
                    }
                  }
                ]
              }
            ]
          }
        ]
      }
  labels:
    app: your-application
  name: your-application-lb
spec:
  ports:
    - port: 443
      name: https
      protocol: TCP
      targetPort: 8080
    - port: 80
      name: http
      protocol: TCP
      targetPort: 8080
  selector:
    app: your-application
  type: LoadBalancer
