metadata:
  namespace: ingress-nginx
rbac:
  create: true
controller:
  replicaCount: 3
  service:
    type: LoadBalancer
    annotations:
      service.beta.kubernetes.io/upcloud-load-balancer-config: |
        {
          "name": "nginx-ingress-loadbalancer",
          "plan": "production-small",
          "frontends": [
            {
              "name": "https",
              "mode": "tcp",
              "port": 443
            },
            {
              "name": "http",
              "mode": "tcp",
              "port": 80
            }
          ],
          "backends": [
          {
            "name": "https",
            "properties": { "outbound_proxy_protocol": "v2"}
          },
          {
            "name": "http",
            "properties": { "outbound_proxy_protocol": "v2"}
          }
        ]
        }
  config:
    use-forwarded-headers: "true"
    compute-full-forwarded-for: "true"
    use-proxy-protocol: "true"
    real-ip-header: "proxy_protocol"
